package com.joshhorowitz.connectfour;

/*
Name: Joshua Horowitz
File: Connect Four Frame
Purpose: To create the UI for the game
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class ConnectFourFrame extends javax.swing.JFrame {

    ConnectFourModel cfm = new ConnectFourModel();
    public int[][] connectFourChips = new int[7][6];
    public int playerMoves = 0; // This determines whether its player Red or Black's turn, Red is odd number, Black is even number
    public int r; // Row variable
    public int c; // Column variable
    public int zeroButtonPressed = 0;
    public int oneButtonPressed = 0;
    public int twoButtonPressed = 0;
    public int threeButtonPressed = 0;
    public int fourButtonPressed = 0;
    public int fiveButtonPressed = 0;
    public int sixButtonPressed = 0;
    private int winVar; // This holds if the game continues, if a tie, or a win

    /**
     * Creates new form ConnectFourFrame
     */
    public ConnectFourFrame() {
        initComponents();
        commentField.setEditable(false);
    }
    
    /**
     * This method is called from any of the drop chip or test buttons to update the Connect Four board data-wise
     * and updates the visual for the players
     * @param r - row
     * @param c - column
     */
    public void chipPlaced(int r, int c) {
        playerMoves++; //Current player's move 
        if (playerMoves == 1) {
            test1Button.setVisible(false);
            test2Button.setVisible(false);
            test3Button.setVisible(false);
        }
        cfm.placeChip(playerMoves, connectFourChips, r, c);
        winVar = cfm.checkforWin(playerMoves, connectFourChips);
        cfm.winloseText(commentField, winVar);
        if (winVar == 0 || winVar == 1 || winVar == 2) {
            zeroButton.setEnabled(false);
            oneButton.setEnabled(false);
            twoButton.setEnabled(false);
            threeButton.setEnabled(false);
            fourButton.setEnabled(false);
            fiveButton.setEnabled(false);
            sixButton.setEnabled(false);
        }
        connectFourPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commentField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        connectFourPanel = new ConnectFourPanel(connectFourChips);
        zeroButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        test1Button = new javax.swing.JButton();
        test2Button = new javax.swing.JButton();
        test3Button = new javax.swing.JButton();
        retryButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        commentField.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        commentField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Connect Four!");

        zeroButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        zeroButton.setText("V");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        oneButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        oneButton.setText("V");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        twoButton.setText("V");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        threeButton.setText("V");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        fourButton.setText("V");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        fiveButton.setText("V");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        sixButton.setText("V");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        test1Button.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        test1Button.setText("Test 1");
        test1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test1ButtonActionPerformed(evt);
            }
        });

        test2Button.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        test2Button.setText("Test 2");
        test2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test2ButtonActionPerformed(evt);
            }
        });

        test3Button.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        test3Button.setText("Test 3");
        test3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test3ButtonActionPerformed(evt);
            }
        });

        retryButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        retryButton.setText("Retry");
        retryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commentField)
                        .addGap(332, 332, 332))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectFourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(test2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(test1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(test3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(157, 157, 157))))
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(557, 557, 557))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(test1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(test2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(test3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(retryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zeroButton)
                            .addComponent(oneButton)
                            .addComponent(twoButton)
                            .addComponent(threeButton)
                            .addComponent(fourButton)
                            .addComponent(fiveButton)
                            .addComponent(sixButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectFourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(commentField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method controls the leftmost drop chip button
     * @param evt
     */
    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        zeroButtonPressed++;
        if (zeroButtonPressed == 6) {
            zeroButton.setEnabled(false);
        }
        r = 0;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_zeroButtonActionPerformed
    
    /**
     * This method controls the second from the left drop chip button
     * @param evt
     */
    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        oneButtonPressed++;
        if (oneButtonPressed == 6) {
            oneButton.setEnabled(false);
        }
        r = 1;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_oneButtonActionPerformed
    
    /**
     * This method controls the third from the left drop chip button
     * @param evt
     */
    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        twoButtonPressed++;
        if (twoButtonPressed == 6) {
            twoButton.setEnabled(false);
        }
        r = 2;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_twoButtonActionPerformed
    
    /**
     * This method controls the fourth from the left drop chip button
     * @param evt
     */
    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        threeButtonPressed++;
        if (threeButtonPressed == 6) {
            threeButton.setEnabled(false);
        }
        r = 3;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_threeButtonActionPerformed
    
    /**
     * This method controls the fifth from the left drop chip button
     * @param evt
     */
    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        fourButtonPressed++;
        if (fourButtonPressed == 6) {
            fourButton.setEnabled(false);
        }
        r = 4;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_fourButtonActionPerformed
    
    /**
     * This method controls the sixth from the left drop chip button
     * @param evt
     */
    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        fiveButtonPressed++;
        if (fiveButtonPressed == 6) {
            fiveButton.setEnabled(false);
        }
        r = 5;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_fiveButtonActionPerformed
    
    /**
     * This method controls the seventh from the left drop chip button
     * @param evt
     */
    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        sixButtonPressed++;
        if (sixButtonPressed == 6) {
            sixButton.setEnabled(false);
        }
        r = 6;
        c = 5;
        chipPlaced(r,c);
    }//GEN-LAST:event_sixButtonActionPerformed
    
    /**
     * This method reads in a file of test data for the game, Test 1 results in player Red winning
     * @param evt 
     */
    private void test1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test1ButtonActionPerformed
        test1Button.setVisible(false);
        test2Button.setVisible(false);
        test3Button.setVisible(false);
        try {
            Scanner test1File = new Scanner(new File("Test data 1.txt"));
            while (test1File.hasNext() == true) {
                r = test1File.nextInt();
                c = 5;
                chipPlaced(r,c);
            }
            test1File.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File not found");
        }
    }//GEN-LAST:event_test1ButtonActionPerformed
    
    /**
     * This method reads in a file of test data for the game, Test 2 results in player Black winning
     * @param evt 
     */
    private void test2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test2ButtonActionPerformed
        test1Button.setVisible(false);
        test2Button.setVisible(false);
        test3Button.setVisible(false);
        try {
            Scanner test2File = new Scanner(new File("Test data 2.txt"));
            while (test2File.hasNext() == true) {
                r = test2File.nextInt();
                c = 5;
                chipPlaced(r,c);
            }
            test2File.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File not found");
        }
    }//GEN-LAST:event_test2ButtonActionPerformed
    
    /**
     * This method reads in a file of test data for the game, Test 3 results in a tie and also a Data Overflow
     * error due to too many moves being made
     * @param evt 
     */
    private void test3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test3ButtonActionPerformed
        test1Button.setVisible(false);
        test2Button.setVisible(false);
        test3Button.setVisible(false);
        try {
            Scanner test3File = new Scanner(new File("Test data 3.txt"));
            while (test3File.hasNext() == true) {
                r = test3File.nextInt();
                c = 5;
                chipPlaced(r,c);
            }
            test3File.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File not found");
        }
        commentField.setText("Tie. (Error: Data Overflow)");
    }//GEN-LAST:event_test3ButtonActionPerformed
    
    /**
     * This method resets the UI so the players can start Connect Four again or load a test file again
     * @param evt 
     */
    private void retryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryButtonActionPerformed
        zeroButton.setEnabled(true);
        oneButton.setEnabled(true);
        twoButton.setEnabled(true);
        threeButton.setEnabled(true);
        fourButton.setEnabled(true);
        fiveButton.setEnabled(true);
        sixButton.setEnabled(true);
        test1Button.setVisible(true);
        test2Button.setVisible(true);
        test3Button.setVisible(true);
        commentField.setText("");
        cfm.resetChips(connectFourChips);
        playerMoves = 0;
        zeroButtonPressed = 0;
        oneButtonPressed = 0;
        twoButtonPressed = 0;
        threeButtonPressed = 0;
        fourButtonPressed = 0;
        fiveButtonPressed = 0;
        sixButtonPressed = 0;
        connectFourPanel.repaint();
    }//GEN-LAST:event_retryButtonActionPerformed
    
    /**
     * This method when Exit is pressed will close the application
     * @param evt 
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField commentField;
    private javax.swing.JPanel connectFourPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton retryButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton test1Button;
    private javax.swing.JButton test2Button;
    private javax.swing.JButton test3Button;
    private javax.swing.JButton threeButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
